- name: 'Frontend: Bug'
  color: 'd73a4a'
  description: Problems related to Svelte
- name: 'Frontend: Enhancement'
  color: 'a2eeef'
  description: Improvements related to the design or functionality of the frontend
- name: 'Backend: Bug'
  color: 'd73a4a'
  description: Problems related to the backend
- name: 'Backend: Enhancement'
  color: 'a2eeef'
  description: Improvements related to the design or functionality of the backend