name: Labeler

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
    paths:
      - '.github/labels.yml'

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    if: github.repository_owner == 'burakys'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Labeler
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          yaml-file: .github/labels.yml
          github-token: ${{ secrets.GH_TOKEN }}